-- MySQL Script generated by MySQL Workbench
-- dom 06 nov 2022 15:27:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `nombre_Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `fecha_Nacimiento` DATE NOT NULL,
  `sexo` CHAR(10) NOT NULL,
  `codigo_Postal` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `fecha_Vencimiento` DATE NOT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_pais1_idx` (`pais_idpais` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist` (
  `idplaylist` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `numero_Canciones` INT NOT NULL,
  `fecha_Eliminacion` DATE NOT NULL,
  `fecha_Creacion` DATE NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `tipo_Playlist` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idplaylist`),
  INDEX `fk_playlist_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artista` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen_Artista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idartista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discografica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discografica` (
  `iddiscografica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddiscografica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `fecha_Publicacion` DATE NOT NULL,
  `imagen_Portada` VARCHAR(45) NOT NULL,
  `artista_idartista` INT NOT NULL,
  `discografica_iddiscografica` INT NOT NULL,
  PRIMARY KEY (`idalbum`),
  INDEX `fk_album_artista1_idx` (`artista_idartista` ASC) VISIBLE,
  INDEX `fk_album_discografica1_idx` (`discografica_iddiscografica` ASC) VISIBLE,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idartista`)
    REFERENCES `mydb`.`artista` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_discografica1`
    FOREIGN KEY (`discografica_iddiscografica`)
    REFERENCES `mydb`.`discografica` (`iddiscografica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`canciones` (
  `idcanciones` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `duracion` DOUBLE NOT NULL,
  `cantidad_Reproducciones` INT NOT NULL,
  `cantidad_Likes` VARCHAR(45) NOT NULL,
  `album_idalbum` INT NOT NULL,
  PRIMARY KEY (`idcanciones`),
  INDEX `fk_canciones_album1_idx` (`album_idalbum` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `canciones_idcanciones` INT NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idgenero`, `canciones_idcanciones`),
  INDEX `fk_genero_canciones1_idx` (`canciones_idcanciones` ASC) VISIBLE,
  CONSTRAINT `fk_genero_canciones1`
    FOREIGN KEY (`canciones_idcanciones`)
    REFERENCES `mydb`.`canciones` (`idcanciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlist_has_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlist_has_canciones` (
  `playlist_idplaylist` INT NOT NULL,
  `canciones_idcanciones` INT NOT NULL,
  PRIMARY KEY (`playlist_idplaylist`, `canciones_idcanciones`),
  INDEX `fk_playlist_has_canciones_canciones1_idx` (`canciones_idcanciones` ASC) VISIBLE,
  INDEX `fk_playlist_has_canciones_playlist1_idx` (`playlist_idplaylist` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_has_canciones_playlist1`
    FOREIGN KEY (`playlist_idplaylist`)
    REFERENCES `mydb`.`playlist` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_has_canciones_canciones1`
    FOREIGN KEY (`canciones_idcanciones`)
    REFERENCES `mydb`.`canciones` (`idcanciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from usuario;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


