-- MySQL Script generated by MySQL Workbench
-- lun 07 nov 2022 22:38:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DH_Noticias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DH_Noticias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DH_Noticias` ;
USE `DH_Noticias` ;

-- -----------------------------------------------------
-- Table `DH_Noticias`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `idestado_UNIQUE` (`idestado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`autor` (
  `idautor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `ciudad_Nacimiento` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idautor`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`articulos` (
  `idarticulos` INT NOT NULL AUTO_INCREMENT,
  `fecha_Creacion` DATE NOT NULL,
  `fecha_Publicacion` DATETIME NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `estado_idestado` INT NOT NULL,
  `autor_idautor` INT NOT NULL,
  PRIMARY KEY (`idarticulos`),
  INDEX `fk_articulos_estado1_idx` (`estado_idestado` ASC) VISIBLE,
  INDEX `fk_articulos_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  UNIQUE INDEX `idarticulos_UNIQUE` (`idarticulos` ASC) VISIBLE,
  UNIQUE INDEX `autor_idautor_UNIQUE` (`autor_idautor` ASC) VISIBLE,
  UNIQUE INDEX `estado_idestado_UNIQUE` (`estado_idestado` ASC) VISIBLE,
  CONSTRAINT `fk_articulos_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `DH_Noticias`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `DH_Noticias`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_Categoria` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcategorias`),
  UNIQUE INDEX `idcategorias_UNIQUE` (`idcategorias` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`subCategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`subCategorias` (
  `idsubCategorias` INT NOT NULL AUTO_INCREMENT,
  `articulos_idarticulos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado_subCategorias` TINYINT(1) NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idsubCategorias`),
  INDEX `fk_subCategorias_articulos_idx` (`articulos_idarticulos` ASC) VISIBLE,
  INDEX `fk_subCategorias_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  UNIQUE INDEX `idsubCategorias_UNIQUE` (`idsubCategorias` ASC) VISIBLE,
  UNIQUE INDEX `articulos_idarticulos_UNIQUE` (`articulos_idarticulos` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `categorias_idcategorias_UNIQUE` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_subCategorias_articulos`
    FOREIGN KEY (`articulos_idarticulos`)
    REFERENCES `DH_Noticias`.`articulos` (`idarticulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subCategorias_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `DH_Noticias`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`recursos` (
  `idrecursos` INT NOT NULL AUTO_INCREMENT,
  `articulos_idarticulos` INT NOT NULL,
  `articulos_estado_idestado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ruta_Relativa` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idrecursos`),
  INDEX `fk_recursos_articulos1_idx` (`articulos_idarticulos` ASC, `articulos_estado_idestado` ASC) VISIBLE,
  UNIQUE INDEX `idrecursos_UNIQUE` (`idrecursos` ASC) VISIBLE,
  CONSTRAINT `fk_recursos_articulos1`
    FOREIGN KEY (`articulos_idarticulos` , `articulos_estado_idestado`)
    REFERENCES `DH_Noticias`.`articulos` (`idarticulos` , `estado_idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`tipo_Recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`tipo_Recursos` (
  `idtipo_Recursos` INT NOT NULL AUTO_INCREMENT,
  `tipo_Recursoscol` VARCHAR(45) NOT NULL,
  `recursos_idrecursos` INT NOT NULL,
  PRIMARY KEY (`idtipo_Recursos`),
  INDEX `fk_tipo_Recursos_recursos1_idx` (`recursos_idrecursos` ASC) VISIBLE,
  UNIQUE INDEX `idtipo_Recursos_UNIQUE` (`idtipo_Recursos` ASC) VISIBLE,
  UNIQUE INDEX `recursos_idrecursos_UNIQUE` (`recursos_idrecursos` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_Recursos_recursos1`
    FOREIGN KEY (`recursos_idrecursos`)
    REFERENCES `DH_Noticias`.`recursos` (`idrecursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`especialidades` (
  `idespecialidades` INT NOT NULL AUTO_INCREMENT,
  `tipo_Especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idespecialidades`),
  UNIQUE INDEX `idespecialidades_UNIQUE` (`idespecialidades` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`autor_has_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`autor_has_especialidades` (
  `autor_has_especialidadescol` INT NOT NULL AUTO_INCREMENT,
  `autor_idautor` INT NOT NULL,
  `especialidades_idespecialidades` INT NOT NULL,
  PRIMARY KEY (`autor_has_especialidadescol`),
  INDEX `fk_autor_has_especialidades_especialidades1_idx` (`especialidades_idespecialidades` ASC) VISIBLE,
  INDEX `fk_autor_has_especialidades_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  UNIQUE INDEX `autor_idautor_UNIQUE` (`autor_idautor` ASC) VISIBLE,
  UNIQUE INDEX `autor_has_especialidadescol_UNIQUE` (`autor_has_especialidadescol` ASC) VISIBLE,
  CONSTRAINT `fk_autor_has_especialidades_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `DH_Noticias`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autor_has_especialidades_especialidades1`
    FOREIGN KEY (`especialidades_idespecialidades`)
    REFERENCES `DH_Noticias`.`especialidades` (`idespecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lugar_Nacimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DH_Noticias`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DH_Noticias`.`comentarios` (
  `articulos_idarticulos` INT NOT NULL AUTO_INCREMENT,
  `articulos_estado_idestado` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `fecha_` DATE NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `estado_` VARCHAR(45) NOT NULL,
  `autor_idautor` INT NOT NULL,
  PRIMARY KEY (`articulos_idarticulos`, `articulos_estado_idestado`, `usuario_idusuario`),
  INDEX `fk_articulos_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_articulos_has_usuario_articulos1_idx` (`articulos_idarticulos` ASC, `articulos_estado_idestado` ASC) VISIBLE,
  INDEX `fk_comentarios_autor1_idx` (`autor_idautor` ASC) VISIBLE,
  UNIQUE INDEX `articulos_idarticulos_UNIQUE` (`articulos_idarticulos` ASC) VISIBLE,
  CONSTRAINT `fk_articulos_has_usuario_articulos1`
    FOREIGN KEY (`articulos_idarticulos` , `articulos_estado_idestado`)
    REFERENCES `DH_Noticias`.`articulos` (`idarticulos` , `estado_idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `DH_Noticias`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_autor1`
    FOREIGN KEY (`autor_idautor`)
    REFERENCES `DH_Noticias`.`autor` (`idautor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
